# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98faf9730e73ea6d611aafbc9b6132bea81f199a166f164243e7237f50a4dde6ddd15db515c7871a2030990a72501c9c775ce2f338e7ca47d3f7575947d8c145

test:
  secret_key_base: eb1ee6a723c6b72f448566c600c7d15c33de8be36988129e2caf97b160a4a03c7ceed0dd103d036c563a4db373f800f266dd9d288254eb6ba9ddad69fe89ad8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
